import Navbar from "./components/Sections/Navbar";
import "./globals.css";
import { Phudu } from "next/font/google";

const phudu = Phudu({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={phudu.className}>
        <div className="bg-gray-50">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
